services:
  my-web-server:
    image: nginx:latest
    container_name: my_nginx
    volumes:
      - html_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    restart: unless-stopped
    depends_on:
      - python-app

  postgres-db:
    container_name: my_postgres
    image: postgres:17.7
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '7777:5432'
    restart: always

  python-app:
    build: ./python_app
    container_name: my_python_app
    volumes:
      - html_data:/app/html_output
    depends_on:
      - postgres-db
    restart: on-failure

volumes:
  pg_data:
  html_data:

networks:
  default:
    driver: bridge
    name: my_net
